#initialCapacity: 1024  #初始的缓存空间大小
#maximumSize: 1024 #缓存的最大条数
#maximumWeight: 100 #缓存的最大权重
#expireAfterAccess: 30 * 60 * 1000 # 最后一次写入或访问后经过固定时间过期
#expireAfterWrite: 30 * 60 * 1000 #最后一次写入后经过固定时间过期
#refreshAfterWrite: 30 * 60 * 1000 #创建缓存或者最近一次更新缓存后经过固定的时间间隔，刷新缓存
#weakKeys: #打开key的弱引用
#weakValues：打开value的弱引用
#softValues：打开value的软引用
#recordStats：开发统计功能


#expireAfterWrite和expireAfterAccess同事存在时，以expireAfterWrite为准。
#maximumSize和maximumWeight不可以同时使用
#weakValues和softValues不可以同时使用

#spring:
#  cache:
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s
#  type: caffeine
